version: "3"
services:
  rest_hotel:
    # container_name: rest_hotel
    build:
      context: ../
    environment:
      # https://learn.microsoft.com/vi-vn/aspnet/core/security/docker-compose-https?view=aspnetcore-6.0
      # 80 for http, 443 for https
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/resthotel.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w0rd!
    ports:
      - "80" # http
      - "443"
    volumes:
      - ./resthotel.pfx:/https/resthotel.pfx
      # - ${USERPROFILE}/.aspnet/https:/https:ro
    networks:
      - resthotel

  nginx:
    container_name: nginx
    hostname: "nginx"
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy.conf:/etc/nginx/proxy.conf:ro
      - ./resthotel.key:/etc/nginx/resthotel.key
      - ./resthotel.pem:/etc/nginx/resthotel.pem
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - rest_hotel
    networks:
      - resthotel
networks:
  resthotel:
    external: true
