version: "3"
services:
  redis:
    container_name: redis
    image: redis
    volumes:
      - redis_stored:/data
    ports:
      - "6379:6379"
    networks:
      - resthotel

  sql:
    container_name: sql
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      #default userid: "sa"
      SA_PASSWORD: pa55w0rd!
      ACCEPT_EULA: "Y"
    networks:
      - resthotel
    volumes:
      - mssqlsystem:/var/opt/mssql
      - mssqluser:/var/opt/sqlserver

volumes:
  redis_stored: {}
  mssqlsystem: {}
  mssqluser: {}

networks:
  resthotel:
    external: true
