# just for testing webhook
version: "3"
services:
  stripe:
    container_name: stripe
    image: stripe/stripe-cli
    command: listen --forward-to roomee.eastasia.cloudapp.azure.com/api/payment/stripe
    environment:
      STRIPE_API_KEY: sk_test_51M3OAAKXzHdAkH9yLzjgAtWoxzlQo1b8FPgTiEPso5OaIlD3JuUErErX9CCx3yoh6yIcrVSDcHcpP7PzJ60DZKpd00ucFNZDao
      STRIPE_DEVICE_NAME: phuc
# host: host.docker.internal
#exec: docker exec -it stripe sh
