name: build and deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -t $username/hotel.api:latest .

      - name: Push the Docker image
        run: |
          docker login -u $username -p $password
          docker push $username/hotel.api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    env:
      private_key: ${{ secrets.PRIVATE_KEY }}
      username: ${{ secrets.DOCKER_USERNAME }}
      remote_server: ${{ secrets.REMOTE_SERVER }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo $private_key > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa $remote_server >> ~/.ssh/known_hosts

      - name: SSH to remote server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa azureuser@$remote_server
          sudo docker service update --image $username/hotel.api:latest hotelserver_rest_hotel
