global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "resthotel"
    static_configs:
      - targets: ["resthotel:80"] #nginx:443

remote_write:
  - url: "http://grafana:3000"
